"""empty message

Revision ID: 04146eebc160
Revises: 47e5dbf8ec1a
Create Date: 2023-03-10 22:33:13.160776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04146eebc160'
down_revision = '47e5dbf8ec1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('Vin',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=17),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"car_Vin_seq"\'::regclass)'))
        batch_op.alter_column('Year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('Year',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('Vin',
               existing_type=sa.String(length=17),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"car_Vin_seq"\'::regclass)'))

    # ### end Alembic commands ###
